---
title: "Econ 216 Final Project"
author: "Kyler Rosen, Raunak Bhumsaria, Gordon Bradley, and Alex Illchev"
date: "`r Sys.Date()`"
output: pdf_document
---


## Background
The dataset we are using is the United States Wind Turbine Database (USWTDB). We retrieved this from: https://eerscmap.usgs.gov/uswtdb/ 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load and Inspect Data

```{r}
# Load necessary libraries
library(tidyverse)
library(lubridate)
library(ggmap)
library(dplyr)

us_map <- map_data("state")


# Load the data
data <- read.csv("uswtdb_v4_3_20220114.csv")

# Inspect the first few rows of the data
head(data)

# Summarize the data to understand its structure
summary(data)
```

## Exploring Relationships

```{r}
# Histograms for continuous variables
continuous_vars <- c("p_cap", "t_cap", "t_hh", "t_rd", "t_rsa", "t_ttlh")
continuous_titles <- c("Turbine Power Capacity (MW)", "Turbine Rated Capacity (MW)", 
                       "Turbine Hub Height (m)", "Turbine Rotor Diameter (m)", 
                       "Turbine Rotor Sweep Area (sq m)", "Total Turbine Height (m)")

binwidths <- c(10, 100, 5, 2.5, 500, 5)


for (i in 1:length(continuous_vars)) {
  var <- continuous_vars[i]
  title <- continuous_titles[i]
  binwidth <- binwidths[i]
  
  print(ggplot(data, aes_string(x = var)) +
          geom_histogram(binwidth = binwidth, fill = "blue", color = "black") +
          labs(x = title, y = "Frequency", title = paste("Distribution of", title)) +
          theme_minimal())
}

```

```{r}
# Bar plots for categorical variables
categorical_vars <- c("t_state", "retrofit", "t_conf_atr", "t_conf_loc")
categorical_titles <- c("State", "Retrofit Status", "Configuration Attribute", "Configuration Location")

for (i in 1:length(categorical_vars)) {
  var <- categorical_vars[i]
  title <- categorical_titles[i]
  
  print(ggplot(data, aes_string(x = var)) +
          geom_bar(fill = "coral", color = "black") +
          labs(x = title, y = "Count", title = paste("Turbine Count by", title)) +
          theme_minimal() +
          theme(axis.text.x = element_text(angle = 90, hjust = 1)))
}

```

```{r}
# Bar plot for year variables
year_vars <- c("p_year", "retrofit_year")
year_titles <- c("Production Year", "Retrofit Year")

for (i in 1:length(year_vars)) {
  var <- year_vars[i]
  title <- year_titles[i]
  
  data[[var]] <- as.factor(data[[var]])
  
  print(ggplot(data, aes_string(x = var)) +
          geom_bar(fill = "green", color = "black") +
          labs(x = title, y = "Count", title = paste("Turbine Count by", title)) +
          theme_minimal() +
          theme(axis.text.x = element_text(angle = 90, hjust = 1)))
}

```

```{r}
# Convert date to Date format
data$t_img_date <- as.Date(data$t_img_date, format = "%m/%d/%Y")

ggplot(data, aes(x = t_img_date)) +
  geom_line(stat = "count", aes(group = 1)) +
  labs(x = "Date", y = "Count", title = "Number of Images Over Time After 2015")

# Filter data for dates after 2015
data_after_2015 <- data %>%
  filter(t_img_date > as.Date("2015-12-31"))

# Aggregate data by month
monthly_data <- data_after_2015 %>%
  group_by(month = floor_date(t_img_date, "month")) %>%
  summarise(count = n())

ggplot(monthly_data, aes(x = month, y = count)) +
  geom_line() +
  labs(x = "Month", y = "Count", title = "Monthly Number of Images Over Time After 2015") +
  theme_minimal()


```

```{r}
register_stadiamaps("f94c64ea-35d9-425f-af7a-e139e3bd6242", write = TRUE)

continental_bbox <- c(left = -125, bottom = 24, right = -66, top = 49)
continental_map <- get_stadiamap(bbox = continental_bbox, zoom = 5, maptype = "stamen_toner_lite")

ggmap(continental_map) +
  geom_point(data = data, aes(x = xlong, y = ylat, color = t_state), size = 1) +
  labs(x = "Longitude", y = "Latitude", title = "Geographic Distribution of Turbines in Continental US") +
  theme_minimal()

alaska_bbox <- c(left = -170, bottom = 52, right = -130, top = 72)
alaska_map <- get_stadiamap(bbox = alaska_bbox, zoom = 4, maptype = "stamen_toner_lite")

ggmap(alaska_map) +
  geom_point(data = data, aes(x = xlong, y = ylat, color = t_state), size = 1) +
  labs(x = "Longitude", y = "Latitude", title = "Geographic Distribution of Turbines in Alaska") +
  theme_minimal()

hawaii_bbox <- c(left = -160, bottom = 18, right = -154, top = 23)
hawaii_map <- get_stadiamap(bbox = hawaii_bbox, zoom = 7, maptype = "stamen_toner_lite")

ggmap(hawaii_map) +
  geom_point(data = data, aes(x = xlong, y = ylat, color = t_state), size = 1) +
  labs(x = "Longitude", y = "Latitude", title = "Geographic Distribution of Turbines in Hawaii") +
  theme_minimal()
  
```

```{r}

# Correlation plot if there are multiple numeric variables
numeric_data <- data %>% select_if(is.numeric)
correlation_matrix <- cor(numeric_data, use = "complete.obs")
print(ggplot(data = as.data.frame(as.table(correlation_matrix)),
       aes(x = Var1, y = Var2, fill = Freq)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0, limit = c(-1,1)) +
  labs(title = "Correlation Matrix of Numeric Variables",
       x = "Variable 1", 
       y = "Variable 2", 
       fill = "Correlation Coefficient") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)))


# End of EDA section with session information
sessionInfo()
```
